import type { Backtest, LivePortfolio, PaperPortfolio, RiskRule, Strategy, WalkforwardResult } from "@/integrations/supabase/types";

const now = new Date().toISOString();

export const mockStrategies: Strategy[] = [
  {
    id: "s1",
    name: "BTC EMA Trend Rider",
    symbol: "BTCUSDT",
    timeframe: "4h",
    asset_class: "crypto",
    description: "Trendfolge mit EMA Crossover und ATR Stop.",
    parameters: { fast: 21, slow: 55, atr: 14 },
    status: "active",
    is_champion: true,
    tags: ["trend", "ema", "btc"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "s2",
    name: "ETH RSI Mean Reversion",
    symbol: "ETHUSDT",
    timeframe: "1h",
    asset_class: "crypto",
    description: "RSI-basierte Reversion in Seitwärtsphasen.",
    parameters: { rsiPeriod: 14, oversold: 28, overbought: 72 },
    status: "active",
    is_champion: false,
    tags: ["mean-reversion", "rsi", "eth"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "s3",
    name: "SOL Donchian Breakout",
    symbol: "SOLUSDT",
    timeframe: "1d",
    asset_class: "crypto",
    description: "Breakout über Donchian Channels mit Volumenfilter.",
    parameters: { channel: 20, volumeMultiplier: 1.5 },
    status: "draft",
    is_champion: false,
    tags: ["breakout", "donchian", "sol"],
    created_at: now,
    updated_at: now,
  },
];

export const mockBacktests: Backtest[] = [
  {
    id: "b1",
    strategy_id: "s1",
    start_date: "2023-01-01",
    end_date: "2025-12-31",
    initial_capital: 10000,
    final_capital: 18450,
    total_return: 84.5,
    cagr: 23.3,
    sharpe_ratio: 1.84,
    max_drawdown: -16.2,
    win_rate: 47.8,
    profit_factor: 1.93,
    total_trades: 68,
    winning_trades: 33,
    losing_trades: 35,
    avg_trade_duration: "3.4 Tage",
    equity_curve: [
      { date: "2025-01", value: 12000 },
      { date: "2025-03", value: 13500 },
      { date: "2025-06", value: 14900 },
      { date: "2025-09", value: 16050 },
      { date: "2025-12", value: 18450 },
    ],
    monthly_returns: { Jan: 4.2, Feb: 1.1, Mar: 3.4 },
    status: "completed",
    created_at: now,
    updated_at: now,
  },
  {
    id: "b2",
    strategy_id: "s2",
    start_date: "2023-01-01",
    end_date: "2025-12-31",
    initial_capital: 10000,
    final_capital: 15100,
    total_return: 51,
    cagr: 15.1,
    sharpe_ratio: 1.21,
    max_drawdown: -12.9,
    win_rate: 56.4,
    profit_factor: 1.41,
    total_trades: 124,
    winning_trades: 70,
    losing_trades: 54,
    avg_trade_duration: "18h",
    equity_curve: [
      { date: "2025-01", value: 11100 },
      { date: "2025-03", value: 11800 },
      { date: "2025-06", value: 12900 },
      { date: "2025-09", value: 14000 },
      { date: "2025-12", value: 15100 },
    ],
    monthly_returns: { Jan: 2.1, Feb: -0.4, Mar: 3.0 },
    status: "completed",
    created_at: now,
    updated_at: now,
  },
];

export const mockWalkforward: WalkforwardResult[] = [
  {
    id: "w1",
    strategy_id: "s1",
    window_number: 1,
    in_sample_start: "2023-01-01",
    in_sample_end: "2024-06-30",
    out_of_sample_start: "2024-07-01",
    out_of_sample_end: "2024-12-31",
    in_sample_sharpe: 1.9,
    in_sample_return: 42,
    in_sample_max_dd: -11,
    out_of_sample_sharpe: 1.4,
    out_of_sample_return: 16,
    out_of_sample_max_dd: -8,
    efficiency_ratio: 0.74,
    optimized_params: { fast: 20, slow: 55 },
    passed: true,
    created_at: now,
  },
  {
    id: "w2",
    strategy_id: "s1",
    window_number: 2,
    in_sample_start: "2023-07-01",
    in_sample_end: "2024-12-31",
    out_of_sample_start: "2025-01-01",
    out_of_sample_end: "2025-06-30",
    in_sample_sharpe: 1.7,
    in_sample_return: 38,
    in_sample_max_dd: -14,
    out_of_sample_sharpe: 1.1,
    out_of_sample_return: 10,
    out_of_sample_max_dd: -9,
    efficiency_ratio: 0.65,
    optimized_params: { fast: 21, slow: 55 },
    passed: true,
    created_at: now,
  },
];

export const mockPaperPortfolios: PaperPortfolio[] = [
  {
    id: "p1",
    strategy_id: "s1",
    initial_capital: 10000,
    current_capital: 10420,
    peak_capital: 10640,
    is_active: true,
    total_pnl: 420,
    total_trades: 12,
    winning_trades: 7,
    losing_trades: 5,
    max_drawdown: -4.3,
    created_at: now,
    updated_at: now,
  },
];

export const mockRiskRules: RiskRule[] = [
  {
    id: "r1",
    strategy_id: null,
    is_global: true,
    max_position_size: 0.1,
    stop_loss_percent: 0.02,
    take_profit_percent: 0.04,
    max_daily_loss: 0.05,
    trailing_stop_enabled: true,
    trailing_stop_percent: 0.015,
    created_at: now,
    updated_at: now,
  },
];

export const mockLivePortfolios: LivePortfolio[] = [
  {
    id: "l1",
    strategy_id: "s1",
    exchange: "binance",
    api_key_name: "main-binance",
    initial_capital: 1000,
    current_capital: 1028,
    is_active: false,
    total_pnl: 28,
    total_trades: 4,
    winning_trades: 3,
    losing_trades: 1,
    max_drawdown: -2.5,
    last_signal_check: now,
    created_at: now,
    updated_at: now,
  },
];
